#!/bin/tcsh
cd ~/work/cms/Top/CMSSW_5_3_13/src/
cmsenv
fitTopTransferFunctions TopQuarkAnalysis/TopMassSemiLeptonic/bin/fitTopTransferFunctions_fromSummer11-coarseEta_Summer12_MadGraph_UnbiasedE_L3_unambiguousOnly_PileUp_Ref_dGauss1D_E_GenSymm_cfg.py >&! ~/work/cms/Top/CMSSW_5_3_13/output/fitTopTransferFunctions_fromSummer11-coarseEta_Summer12_MadGraph_UnbiasedE_L3_unambiguousOnly_PileUp_Ref_dGauss1D_E_GenSymm.log
fitTopTransferFunctions TopQuarkAnalysis/TopMassSemiLeptonic/bin/fitTopTransferFunctions_fromSummer11-coarseEta_Summer12_MadGraph_UnbiasedE_L3_unambiguousOnly_elecs_PileUp_Ref_sGauss1D_E_AltGenSymm_cfg.py >&! ~/work/cms/Top/CMSSW_5_3_13/output/fitTopTransferFunctions_fromSummer11-coarseEta_Summer12_MadGraph_UnbiasedE_L3_unambiguousOnly_elecs_PileUp_Ref_sGauss1D_E_AltGenSymm.log
fitTopTransferFunctions TopQuarkAnalysis/TopMassSemiLeptonic/bin/fitTopTransferFunctions_fromSummer11-coarseEta_Summer12_MadGraph_UnbiasedE_L3_unambiguousOnly_muons_PileUp_Ref_sGauss1D_E_GenSymm_cfg.py >&! ~/work/cms/Top/CMSSW_5_3_13/output/fitTopTransferFunctions_fromSummer11-coarseEta_Summer12_MadGraph_UnbiasedE_L3_unambiguousOnly_muons_PileUp_Ref_sGauss1D_E_GenSymm.log
